#!/usr/bin/env bash
# Ignore SC2154

apt-get update -y
apt-get install -y nginx

HOSTNAME=$(hostname)

cat > /etc/nginx/conf.d/custom_header.conf <<EOF
add_header X-Served-By $HOSTNAME always;
EOF

nginx -t

service nginx restart