#!/usr/bin/env bash
# Configure HAProxy load balancer

apt-get -y update
apt-get -y install haproxy

cat > /etc/haproxy/haproxy.cfg <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend haproxy_front
    bind *:80
    default_backend haproxy_backend

backend haproxy_backend
    balance roundrobin
    server web-01 3.91.180.172:80 check
    server web-02 18.212.73.129:80 check
EOF

service haproxy restart