#!/usr/bin/env bash
# Configure Nginx to redirect /redirect_me

set -e

apt-get update -y
apt-get install -y nginx

if ! grep -q "location /redirect_me" /etc/nginx/sites-available/default; then
    sed -i "/server_name _;/a\\
\\
    location /redirect_me {\\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\
    }" /etc/nginx/sites-available/default
fi

nginx -t
systemctl restart nginx