#!/usr/bin/env bash
# Configure Nginx to redirect /redirect_me

set -e

apt-get update -y
apt-get install -y nginx

cat >/etc/nginx/sites-available/default <<'EOF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
EOF

nginx -t
systemctl restart nginx